try {
  throw new Error("Explotó");
} catch {
  console.log("Dió un error");
}
